### ISSUE TITLE
Illustrative project thumbnails

### ISSUE THREAD

**Issue by taylortrimble** [teslaworksumn/teslaworks.net#107]
I'd like to:
- Have more spacing around project thumbnails
- Have a different (maybe thicker or darker) border on them to see them better
- Have different styling perhaps for { current, starting new, past } projects
- Uniform height on projects in a row (probably with jQuery)

**Comment by mplewis** [comment]
I would like more padding around the inner text in thumbnails. 5 px looks good.

Example: http://z.kesdev.com/image/2l3400432224

Code: http://z.kesdev.com/image/291D2z150E2p

**Comment by taylortrimble** [comment]
That's actually what I meant by the first bullet, ha. Said it backwards. Youuuu betcha!

(Also inline styles are the devil)
