### ISSUE TITLE
Tumblr theme build

### ISSUE THREAD

**Issue by taylortrimble** [teslaworksumn/teslaworks.net#127]
Hey! I'm wondering if we can't take advantage of the Flask/Jinja templating system to update our Tumblr theme for us. That way each time we update the masthead, etc we aren't changing the theme too (or forgetting too).

Maybe this could also come with a hook to literally deploy it to Tumblr too!

**Comment by mplewis** [comment]
I can't find a deploy hook for Tumblr: http://themes.themaxdavis.com/tutorial/installing_a_theme

**Comment by taylortrimble** [comment]
Neither could I. Could we at least have it auto-build (auto-update), even if we have to manually copy-and-paste it to set it?

**Comment by taylortrimble** [comment]
This isn't a priority for me anymore. We can reopen it later if we commit to doing it again.
