### ISSUE TITLE
Report 500s

### ISSUE THREAD

**Issue by taylortrimble** [teslaworksumn/teslaworks.net#129]
We were getting some 500s on a (quite old) version of the site earlier today. Luckily the individual reported it.

We should probably roll up some form of 500 reporting so we know when it happens.

**Comment by mplewis** [comment]
http://flask.pocoo.org/docs/errorhandling/#application-errors

**Comment by taylortrimble** [comment]
Exactamundo!

**Comment by bendemaree** [comment]
If you guys want to go full-throttle, I'm a big fan of [Sentry](https://getsentry.com/welcome/) and have it deployed all over the place.

**Comment by mplewis** [comment]
I love the look of this. I'd be happy to implement once we have a Docker
host up.

**Comment by taylortrimble** [comment]
I'm confused about their pricing model - it's open source, so their pricing is forrrr... storage? Just mixed in for good measure?

If we can avoid the monthlies, I'd appreciate it. Web money is tight for student groups.

Of course, there is a free tier and it certainly could be enough! As a note, let's shoot for around $20/month for the site. We're at zero now (if mailgun usage stays low).

Thanks!

**Comment by bendemaree** [comment]
Ah, should've clarified; their hosted version is paid. If you host yourself it's free, $0, like a bird. It's on pip so you know how easy it is. :smile:

**Comment by taylortrimble** [comment]
:open_mouth::open_mouth::open_mouth::open_mouth::open_mouth::open_mouth::open_mouth::open_mouth::open_mouth::open_mouth::open_mouth::open_mouth::open_mouth::open_mouth::open_mouth:
:heart_eyes::heart_eyes::heart_eyes::heart_eyes::heart_eyes::heart_eyes::heart_eyes::heart_eyes::heart_eyes::heart_eyes::heart_eyes::heart_eyes::heart_eyes::heart_eyes::heart_eyes:

**Comment by mplewis** [comment]
I'm so happy to hear this. :cop:

Let's Docker this bitch.

**Comment by taylortrimble** [comment]
Awwww yeaaahhh
