### ISSUE TITLE
Investigate the use of pipework to wire Docker containers together

### ISSUE THREAD

**Issue by mplewis** [teslaworksumn/teslaworks.net#132]
https://github.com/jpetazzo/pipework

If we do it right, we can serve traffic from an arbitrary number of containers with one properly-configured nginx container.

**Comment by mplewis** [comment]
Alternatively we can bundle Sentry into our server builds. This might not be bad, but now we need a persistent DB to save data.

**Comment by taylortrimble** [comment]
This is deploy repo stuff, man!

**Comment by taylortrimble** [comment]
We can build Sentry into twnet. A docker build would create the db, and docker run just wouldn't obviate it, right?

**Comment by mplewis** [comment]
Oops sorry! I'll move it there.
