### ISSUE TITLE
Update website data

### ISSUE THREAD

**Issue by taylortrimble** [teslaworksumn/teslaworks.net#138]
Peter mentioned that some updates were made on the sheet. Can go to File > Version History to see the change deltas.

Also, I guess the Ultralight and Strandbeest project "needs" are wonky/duplicated/switched/something.

**Comment by taylortrimble** [comment]
Also now a new project, "Open Data Initiative". And I'm going to add the Tshirt link.

**Comment by taylortrimble** [comment]
@wagne763 It appears all the updated website data is for the ultralight. I need two things though:
1. I can't reach the Basecamp asset picture
2. The third picture is too small: I need 1500x1000 minimum

The rest will go up.

**Comment by taylortrimble** [comment]
I asked for ODI pictures as well, hope to get those in. Just waiting on pictures now.

**Comment by wagne763** [comment]
Thanks for updating the ultralight page, but we actually aren't building an Easy Riser (that was a decision from a couple weeks ago). The most recent information is here: https://basecamp.com/2133264/projects/2109407-website/messages/15840911-ultralight

The ONLY large enough picture I can find is this: http://www.oshkosh365.org/uploadedFiles/Temp_OshKosh365/Forums/General_EAA_Discussion_Board/fp303_2.jpg

**Comment by taylortrimble** [comment]
I can't see that project: copy the info over to the Website BC please!

> The ONLY large enough picture

You'll need to have him make some sketches then and take some hi-res photos then. #problemsolving

**Comment by wagne763** [comment]
The link I posted is a link to the discussion on the Website BC. You definitely have access.

**Comment by taylortrimble** [comment]
Derrrrrp right you are, I misread the link. Instead of clicking, for some reason. :smile:

Ask your bro to boil that down to one sentence like the other front page projects and shoot me the other two images – I can update today.

**Comment by wagne763** [comment]
For the tagline just replace "Easy Riser" with "Fisher FP-303". We also want the full text from the BC post on the webpage.

**Comment by taylortrimble** [comment]
Images forthcoming?
