### ISSUE TITLE
Email confirmation of project submission

### ISSUE THREAD

**Issue by taylortrimble** [teslaworksumn/teslaworks.net#141]
The flash is a little ephemeral, and maybe not enough.

**Comment by mplewis** [comment]
I don't know if a) we need to send an email, b) we want to burn credits.

What about a fancy full page landing with big happy letters confirming a project submission?

**Comment by taylortrimble** [comment]
I'd rather pop them back to a context where they can get back to doing something again. Looking at more projects probably. Actually makes me want to change the current redirect back to the project page they originated from on a join or ask submission!

We definitely have the credits to burn, and actually, establishing an email line of communication could be very valuable for both parties. Emails that are replied to and forwarded drive better sending reputation (and hence, deliverability) with email providers, and if we can create an open line of communication within the service to and from the officers, they could help project managers who have questions during the process.

One thing that I don't like about the email solution is that it's not Basecamp, and I'm trying to get people to ditch email for using Basecamp instead. Maybe instead I'll try and think of a clever way to integrate with Basecamp.

**Comment by taylortrimble** [comment]
On second thought, the green banner we already have and a same-day response of some form from an officer would be the ideal solution. I only have one case where someone didn't realize their project was submitted, and that doesn't justify development time yet.
