### ISSUE TITLE
Migrate all data to Postgres

### ISSUE THREAD

**Issue by taylortrimble** [teslaworksumn/teslaworks.net#143]
We should also implement a JSON or CSV import/export function to be safe about backups.

@mplewis, I trust you will know some swanky common practice, paradigm, or service to fit our needs. :)

**Comment by mplewis** [comment]
We should just be backing up Postgres style: http://www.postgresql.org/docs/8.1/static/backup.html

**Comment by taylortrimble** [comment]
SQL dump ftw! We’ll have to set up some FTP location and cron job. But cron jobs are sorta old-skool, so maybe a Python timer thingy instead. That could report to Sentry pretty easily too.

**Comment by taylortrimble** [comment]
@mplewis Do you want to push up your branch so I can follow?

**Comment by mplewis** [comment]
I haven't yet made any progress on the Flask side. As such, I have no
branch to push! :)

**Comment by taylortrimble** [comment]
Didn’t you have some form stuff? Or was that just for experimentation?

**Comment by mplewis** [comment]
Yep, that was for experimentation. I can push that if you'd like however.

**Comment by taylortrimble** [comment]
Nah. Have fun!

**Comment by mplewis** [comment]
Working on moving the controllers over now.
