### ISSUE TITLE
TW gear for browser tab image 

### ISSUE THREAD

**Issue by laugh039** [teslaworksumn/teslaworks.net#154]
![tesla works final gear only](https://f.cloud.github.com/assets/4020504/1302324/dab537fe-3132-11e3-931e-c8c64de993ba.png)

Are you sure you need logo design helper friend? Can you use this? I could give you the .ai or the gear with the grid if you wanted those too. I have a lot of logo stuff on my comp.

**Comment by taylortrimble** [comment]
It needs to look good at 32 pixels 32 pixels, so it will probably need to be redone. You can try sucking out as much detail as possible and seeing how good it looks though. You need to remove a ton of detail and still have it look like the same thing though, which is an art all to itself.

**Comment by laugh039** [comment]
Alright, I'll send my dude a text.

**Comment by FourierTransformer** [comment]
Post the ai file, I'll see if I can reduce it for funzies

**Comment by taylortrimble** [comment]
Cool!

**Comment by taylortrimble** [comment]
@FourierTransformer @laugh039 Update?

**Comment by FourierTransformer** [comment]
Only 16x16 had to have some work done (looks OK in my opinion - too many flipping spokes...). I was able to get the others down to a reasonable size while still looking good.

https://dl.dropboxusercontent.com/u/31708279/TeslaFavicon.zip

**Comment by taylortrimble** [comment]
Whoa, a lot of files! I know what to do with:
- `favicon.ico`
- Apple precomposed favicons

The rest I am not sure about. Do I just plop them down, or do I need to <link> them correctly? Interestingly, for the Apple precomposed ones, they don't need a link to work on iOS, but Android uses them too and _does_ require a link. :smiley:

**Comment by taylortrimble** [comment]
Also, nice job!

**Comment by mplewis** [comment]
Re: multiple favicons:

http://davidwalsh.name/retina-favicons

**Comment by taylortrimble** [comment]
Thanks, but that only shows me how to use the ones I already know how to use. ;)
