### ISSUE TITLE
De-duplicate DB connections

### ISSUE THREAD

**Issue by mplewis** [teslaworksumn/teslaworks.net#165]
Right now we have two connections to the Postgres DB: one in `projects_controller.py`, and another in `redirects_controller.py`.

We should minimize this by moving the server connection into its own module.

**Comment by taylortrimble** [comment]
I've noticed that when we lose our connection to the DB, it stays lost but our app doesn't crash. This means we can enter a state where the site stops functioning and can't fix itself!

That's probably it's own issue, but maybe we would fix it while fixing this guy. If not, let's fix that.

**Comment by mplewis** [comment]
What could fix it?

Watchdog to reboot server if DB crashes?

DB disconnect callback to attempt reconnect?

Is there something in psycopg that might do this for us?

**Comment by taylortrimble** [comment]
I'm not big on watchdogs. Kind of inelegant, hacky. Like saying "it's okay if it's down for _this_ long". DB disconnect callback can be a hacky fix too, we can intercept Python's exception handler to call sys.exit when our connection is faily. Then our reloader takes care of us.

psycopg2 doesn't do anything for us, but PgBouncer may be workable.
