### ISSUE TITLE
Make 404 page references absolute, not relative

### ISSUE THREAD

**Issue by mplewis** [teslaworksumn/teslaworks.net#20]
Otherwise browsers can't find our CSS and everything gets gross.

This is a problem if you get 404'd anywhere but at the root directory.

**Comment by taylortrimble** [comment]
Sorry, I couldn't figure this out looking at the code – can you give me steps so I can see what this means in a browser? With some code context if it's not obvious after the browser test?

**Comment by mplewis** [comment]
Sure, this is mostly an HTML/CSS issue.

It involves rewriting the `main.html` template _just_ for the 404 template
so that references to `static/css/bootstrap.css` point to
`/static/css/bootstrap.css` instead.

**Comment by taylortrimble** [comment]
How come the 404 doesn't work but the others do? I believe you, I just don't get it and I'm curious. :smile:

**Comment by mplewis** [comment]
If you go to `teslaworks.net/dsfargeg.html`, your browser is searching for `teslaworks.net/static/css/bootstrap.css`, among other files.

If you go to `teslaworks.net/dsfargeg/index.html`, your browser is searching for `teslaworks.net/dsfargeg/static/css/bootstrap.css`, which is bad because that doesn't exist. It's searching relative to its current directory, `/dsfargeg`.

**Comment by taylortrimble** [comment]
Rawsome! Are we going to run into issues when we really are trying to serve (theoretically) `teslaworks.net/projectname/specialnewpage` in the possible future?

**Comment by mplewis** [comment]
That's a good question. Can we burn that bridge when we come to it? Also,
probably yes? We'll do extensive testing before we deploy :D

**Comment by taylortrimble** [comment]
Yes, I'm fine with putting it off! I don't feel like we're going into serious technical debt with that.

Now, you're going to go **_WHAT!?_** at this:
We should make the 404 and other error pages static, served from the public folder. This is general practice so I'm okay with it. :grin:

**Comment by mplewis** [comment]
Haha, actually that makes total sense, since it _is_ a 404 page.

**Comment by taylortrimble** [comment]
#22 covers this now.
