### ISSUE TITLE
Add Twitter

### ISSUE THREAD

**Issue by mplewis** [teslaworksumn/teslaworks.net#29]
Somehow. Sometime later.

**Comment by mplewis** [comment]
Let's look into https://code.google.com/p/python-twitter/. We can't do any simple client-side JS pulls thanks to the new Twitter auth API stuff, so we need to implement a server-side Twitter pull then send that to the client.

**Comment by taylortrimble** [comment]
Not a fan of this, 5 months later. Permission to decommission?

**Comment by mplewis** [comment]
Yeah. I don't think the TW twitter is being used effectively. Closed.
