### ISSUE TITLE
Improve documentation

### ISSUE THREAD

**Issue by mplewis** [teslaworksumn/teslaworks.net#39]
The current `readme.md` is cute but we do need a little substance.

**Comment by taylortrimble** [comment]
What do you want to see in this?

I'm thinking:
- How to add projects
- What sizes to make images
- Guidelines on other data formatting
- Explaining the Basecamp integrations
- How to ask us for improvements
- Pointing to a wiki page of tests we need to add
- License call out
- "don't put sensitive data in this repo"
- Important color schemes?
- Note about Tumblr

And more important things I'm sure, that's just off the top of my head.

**Comment by taylortrimble** [comment]
- Config vars, incl `DEBUG_EMAIL`

**Comment by taylortrimble** [comment]
- Data format/keys

**Comment by taylortrimble** [comment]
- Docstrings (from #160)
