### ISSUE TITLE
Bootstrap 3 – Let's get ready!

### ISSUE THREAD

**Issue by taylortrimble** [teslaworksumn/teslaworks.net#43]
`.row-fluid` has been dropped in BS3. Let's refactor `bootstrap-mktg-narrow.css` out and recreate its narrow-ness with a `.span6` or `.span8`.

This will also majorly mess with our internal template spans inside `.row-fluid` `div`s.

**Comment by mplewis** [comment]
From the Bootstrap 3 PR:

> all the rows will now be fluid instead of fixed widths

Doesn't this mean we just have to change `.row-fluid` to `.row` when we upgrade?

**Comment by taylortrimble** [comment]
Awww nice. Misinterpreted a different update, good catch. I think that is right!
