### ISSUE TITLE
Add a function to ProjectsController to reload projects from file system

### ISSUE THREAD

**Issue by mplewis** [teslaworksumn/teslaworks.net#44]
This way we can link in a web / code hook to update the project list on demand.

**Comment by taylortrimble** [comment]
Is somebody other than our app going to be editing the project files?

**Comment by mplewis** [comment]
I expect the end-user admins will be editing project files through our app via an admin interface, but that should be it. I foresee this hook being called when a project is [created | updated | deleted].

**Comment by taylortrimble** [comment]
In that case, we expect this workflow:
1. Visit admin panel
2. Edit project list in memory
3. Write project list out

Therefore no reload is required, since the in-memory copy is what was written out anyway.

**Comment by mplewis** [comment]
Never mind, that makes sense! Sounds good to me.
