### ISSUE TITLE
Investigate use of Prefixfree for simplifying CSS prefixes

### ISSUE THREAD

**Issue by mplewis** [teslaworksumn/teslaworks.net#46]
http://leaverou.github.io/prefixfree/

**Comment by taylortrimble** [comment]
Initially unconvinced, this is growing on me.

**Comment by taylortrimble** [comment]
Prefixfree definitely wins cool points, though I'd rather [solve this with SASS mixins](https://github.com/teslaworksumn/teslaworks.net/pull/170/files#diff-00efee36cc0d48843bccc390b6022a6dR1) now. Close?

**Comment by taylortrimble** [comment]
@mplewis says close.
