### ISSUE TITLE
Collapse toolbar nav items on mobile

### ISSUE THREAD

**Issue by taylortrimble** [teslaworksumn/teslaworks.net#57]
Right now, for the Audio Project Page, everything is too wide and moves to 2 lines, looking bad while doing so.

**Comment by taylortrimble** [comment]
Hard. Just tried a couple things, but this might end up being:
1. Distant future
2. Solved by customizing the bootstrap navbar to not look like a nav bar

**Comment by mplewis** [comment]
Screenshots and mockups?

**Comment by taylortrimble** [comment]
I'm going to close this. I don't even really want to do it anymore, because it looks OK right now. Will reopen if you think it's worthwhile.
