### ISSUE TITLE
Deployable

### ISSUE THREAD

**Issue by taylortrimble** [teslaworksumn/teslaworks.net#6]
Hey @mplewis or @bendemaree! I'd like for this to be deployable to teslaworks-rso.sua.umn.edu because we might as well start on that now.

With a README description? Anyone want to tackle? One-liner deploys are fun too.

**Comment by mplewis** [comment]
I'm on it after dinner.

**Comment by taylortrimble** [comment]
How'd this go?

**Comment by mplewis** [comment]
I, um. Forgot to do it. :grimacing:

This also looks a bit harder than I thought at first, so I am going to tactically put this off until I have a little more time. Sorry.

**Comment by taylortrimble** [comment]
No problem: thanks!
