### ISSUE TITLE
Masthead hover isn't working properly on currently-selected link

### ISSUE THREAD

**Issue by mplewis** [teslaworksumn/teslaworks.net#60]
If I hover over the `Home` pill and I'm already at home (the pill is blue), I should see the pill darken.

**Comment by taylortrimble** [comment]
Hmm. Okay, I guess that makes sense.

**Comment by mplewis** [comment]
I guess, kinda. This isn't implemented in the bootstrap-mktg-narrow thingy, you still want to improve it? I don't mind either wya.

**Comment by taylortrimble** [comment]
Yeah, we'll improve it.

**Comment by taylortrimble** [comment]
Closed by #99.
