### ISSUE TITLE
Use ABQ pics

### ISSUE THREAD

**Issue by taylortrimble** [teslaworksumn/teslaworks.net#64]
Cf laugh039/use_ABQ_pics#1.

@laugh039, which 3 do you want us to use?

**Comment by taylortrimble** [comment]
I kind of like the first, the third, and the last.

**Comment by mplewis** [comment]
Out of the 6 shown, I like 1, 2, 3, and 5.

**Comment by laugh039** [comment]
You pick! I like them all, I put them there.

**Comment by taylortrimble** [comment]
Done
