### ISSUE TITLE
Use this for Trevor's pic on website

### ISSUE THREAD

**Issue by laugh039** [teslaworksumn/teslaworks.net#76]
![skydivesmile](https://f.cloud.github.com/assets/4020504/1092475/463e408e-167f-11e3-86c6-001f315728fb.jpg)

**Comment by taylortrimble** [comment]
We're going to make it a face shot only: still want this one?

**Comment by laugh039** [comment]
Yea. It would be cool if you could leave part of the horizon in the lower left.

-----Original Message-----

**Comment by taylortrimble** [comment]
All right, closed by #97.
