### ISSUE TITLE
Blog content

### ISSUE THREAD

**Issue by taylortrimble** [teslaworksumn/teslaworks.net#78]
@wagne763 @laugh039 this is **you guys!**

Our viewers are getting a nasty crap example post on the blog when they visit "News" now. Somethings need to happen there.
1. **Very** well written posts need to be made for each of our past projects
2. Do number 1. Better this time.
3. Really good job with number 2.
4. Okay. Now we need to back post other cool things we did. News, events, Kaler visiting. This is where our "cred" goes, so do it up right!
5. You need to give me special links **_IF_** you want me to make them. Each of the projects I'll give one automatically, but if you want your post about IDEO coming to be at teslaworks.net/ideo13 you need to tell me.

**Comment by taylortrimble** [comment]
When do you guys think you can be done with this? It is very important that we don't pound these out too quick. We need to do them right. But yeah, also fast. I'd prefer it's done before next Friday's meeting. Sorry for the writing assignment. :stuck_out_tongue_winking_eye:

**Comment by taylortrimble** [comment]
Light show! http://giving.umn.edu/extras/AuroraDigitalis/

**Comment by laugh039** [comment]
Rubens' Tube is done with Matt H's help.

**Comment by taylortrimble** [comment]
That's **amazing!** Sweet!

**Comment by laugh039** [comment]
Light Show post is done with help from Kanad!

**Comment by taylortrimble** [comment]
Kanad was a super cool dude! Thanks for introducing him and stuff. I'm glad that one is done, it's super important!

**Comment by taylortrimble** [comment]
This is kind of coming along. I think we're still missing over half of them, but that's a social issue at this point.
