### ISSUE TITLE
Highlight meeting times at top

### ISSUE THREAD

**Issue by taylortrimble** [teslaworksumn/teslaworks.net#80]
I just realized that this is a _super_ common reason people should come visit our site. It's easier to remember teslaworks.net than Friday at 5pm in Keller 3-230.

Mockup attached
![dates](https://f.cloud.github.com/assets/1058478/1092817/54a01190-168c-11e3-9b2b-5ec0b766a57a.png)

**Comment by wagne763** [comment]
This is a great improvement, but I think that the header still needs work. When I open teslaworks.net on my laptop, I see this:

![untitled](https://f.cloud.github.com/assets/5395093/1095817/548d769c-16f1-11e3-941d-14d0ffee4ee9.png)

Just a logo and a slogan do not help me to understand what this group actually does. I need a smaller logo and slogan and more information.

![untitled - copy](https://f.cloud.github.com/assets/5395093/1095810/18c0db68-16f1-11e3-9b7b-76bd8a22cb4b.png)

**Comment by wagne763** [comment]
Oops sorry I uploaded those images in the wrong order, exchange their places to understand what I mean.

**Comment by taylortrimble** [comment]
I flipped them the right way. It's just markdown, if you have the edit button that is.

As for the sentences up top: give me an idea of what you'd like to see. One sentence is all people will read though. 1 sentence = 1 sentence read, 2 sentences = 0 read. So "Be a part of awesome engineering and design projects" is _supposed_ to fill the "explaining what our group does" need, I can see the need for improvement.

One (mandatory) tip: use lots of context. Don't repeat anything a viewer would likely know (like that we're U of M based, a student group, …). That info should **not** go at the top of the page.
