### ISSUE TITLE
FAQ Redo

### ISSUE THREAD

**Issue by taylortrimble** [teslaworksumn/teslaworks.net#86]
New FAQ layout:
- Instead of Question and Answer, formatted like:
#### Would you make a good member?

Our group attracts the brightest self-starters and people interested in gaining tons of hands-on experience. Engineers, designers, scientists, and artists especially love our group, but we have members from many other disciplines as well.
#### Wondering how you can help?

The best way to find out is to learn more about the projects. Find a project that interests you, and let the project manager know what looks interesting to you.
#### What about skill level and time commitment?

Any.
#### Can't make the meeting?

That's okay. Most projects meet on their own at other times during the week. Go to a project page to see when.

In fact, I kind of like those FAQs. Loading them up soon, and not doing that bullshit nasty-looking-anyway collapse thing anymore.

**Comment by wagne763** [comment]
Not sure I understand the difference here between what we had before.

**Comment by taylortrimble** [comment]
The way the questions are presented is different, and I don't want them to collapse.
