### ISSUE TITLE
Add app routes

### ISSUE THREAD

**Issue by taylortrimble** [teslaworksumn/teslaworks.net#9]
I think that our URL structure just gets to be as simple as our site is.
- `/` is just the home page
- `/blog` goes to our blog
- `/<project_name>` goes to the project

No projects named "blog".

Th-th-th-th-that's all folks! :pig: Whaddaya think?

**Comment by mplewis** [comment]
How about `/projects/<project_name>/` for projects?

**Comment by taylortrimble** [comment]
More than I want to type. I want to be able to tell people "oh yeah you like my project? go to teslaworks.net/robosaic" Smaller and easier to remember.

**Comment by taylortrimble** [comment]
Didn't think about the blog URLs at _all_. Can we pass those to flasktopress somehow?

**Comment by mplewis** [comment]
Sure. I like that. Elaborate on blog URLs?

**Comment by taylortrimble** [comment]
If someone wants to share our article about how Tesla Works invented the next generation of dog toys, we need blog URLs.

But I think I just remembered how Jekyll works and that should be no big deal. It can "know" that it's hosted at `teslaworks.net/blog` and generate the appropriate `teslaworks.net/blog/2013/06/16/matt-and-taylor-decide-on-site-routes` URLs.

**Comment by mplewis** [comment]
Yeah, you can set the base URL for Jekyll/Octo just like that!
