### ISSUE TITLE
Data transfer from old website

### ISSUE THREAD

**Issue by wagne763** [teslaworksumn/teslaworks.net#93]
I see that you guys are trying to write up blog posts and summaries for tw.net about each of the projects. This information was all available on the old website, so to get started we need to copy over what we had before. Although we have a backup, it would be EXTREMELY cumbersome to try and extract the data from that. Far better would be to create a scratch domain and point it to the 000webhost nameserver so that we can copy things over in a human-friendly fashion. Can somebody set this up, please?

**Comment by taylortrimble** [comment]
We’ll need to go back and improve those stories we have not anyway. That’s okay, we still need them up.

When that time comes, I can write some tools to extract the info we need from what we had before.

Good idea, I tried to get them to help, but they’re… we got what we paid for. ;)

**Comment by mplewis** [comment]
Can we set up a subdomain? old.teslaworks.net? or old.thenewtricks.com?

**Comment by taylortrimble** [comment]
Nope. Once you pick a domain on 000webhost, you can't change it. That goes for using a subdomain too.
